version: 8.2.15
docker_context: .
build_docker_file: docker/Dockerfile.building
build_method: pytest_run
update_method: python_update
python_version_file: frontik/version.py
deploy_method: nope_deploy
type: library
changelog: true
