#!/usr/bin/env python3
# coding=utf-8

import asyncio
from frontik.server import FrontikServer

if __name__ == '__main__':
    frontik_server = FrontikServer('tests/projects/frontik_debug.cfg')
    asyncio.run(frontik_server.run())
