# syntax=docker/dockerfile:1.4
FROM registry.pyn.ru/python3.9-bullseye-building:2025.01.28

RUN mkdir -p -m 0600 ~/.ssh && ssh-keyscan forgejo.pyn.ru >> ~/.ssh/known_hosts

COPY frontik-test README.md MANIFEST.in /home/building/
COPY poetry.lock pyproject.toml /home/building/
COPY frontik /home/building/frontik/
COPY tests /home/building/tests/
COPY examples /home/building/examples/
WORKDIR /home/building

RUN --mount=type=ssh poetry install --no-root --all-extras
