from frontik import etree

foot_xml = etree.fromstring('''<foot>
  <foot-item>
    <href>http://hh.ru</href>
    <text>foot.press</text>
  </foot-item>
  <foot-item>
    <href>http://hh.ru</href>
    <text>foot.about</text>
  </foot-item>
  <foot-item>
    <href>http://hh.ru</href>
    <text>foot.research</text>
  </foot-item>
  <foot-item>
    <href>/feedback.mvc</href>
    <text>leftMenu.feedback</text>
  </foot-item>
  <hh-foot>
    <foot-top>
      <item>
        <href>/article/2</href>
        <text>contents.footer.applicants</text>
      </item>
      <item>
        <href>/article/3</href>
        <text>contents.footer.employers</text>
      </item>
      <item>
        <href>/article/4</href>
        <text>contents.footer.agencyes</text>
      </item>
      <item>
        <href>/article/8</href>
        <text>headhunter.reclame.title</text>
      </item>
      <item>
        <href>/article/176</href>
        <text>requirements.title</text>
      </item>
      <item>
        <href>/article/399</href>
        <text>footer.headhunter.partners</text>
      </item>
    </foot-top>
    
    <foot-bottom>
      <item>
        <href>/article.do?articleId=28</href>
        <text>contents.footer.about</text>
      </item>
      <item>
        <href>/article.do?articleId=132</href>
        <text>contents.footer.research</text>
      </item>
      <item>
        <href>/feedback.mvc</href>
        <text>leftMenu.feedback</text>
      </item>
      <item>
        <href>/article/112</href>
        <text>contents.footer.calendar</text>
      </item>
    </foot-bottom>
  </hh-foot>
</foot>''')

def do_foot(response):
    response.doc.put(foot_xml)