---
name: Python package
on:
  pull_request:
    types: [opened, reopened]
    branches: [master]
  pull_request_sync:
    branches: [master]
  push:
    branches: [master]

jobs:
  build:
    runs-on: ${{ vars.RUNNER_NAME }}
    container:
      image: registry.pyn.ru/python3.12-node22-bookworm-building:2025.01.11
      credentials:
        username: ${{ secrets.INFRA_REGISTRY_ACC_LOGIN }}
        password: ${{ secrets.INFRA_REGISTRY_ACC_PASSWORD }}

    steps:
      - name: Checkout
        uses: https://forgejo.pyn.ru/actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: https://forgejo.pyn.ru/actions/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Install poetry
        run: |
          python -m pip install poetry

      - name: Install package
        run: |
          poetry install

      - name: Test with pytest
        run: |
          python -m poetry run pytest

      # true if cache-hit occured on the primary key
      - run: echo '${{ steps.pinstall.outputs.cache-hit }}'
#      - name: Lint with flake8
#        run: |
#          # stop the build if there are Python syntax errors or undefined names
#          # flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
#          # exit-zero treats all errors as warnings
#          flake8 . --count --exit-zero --max-complexity=10 --statistics
