---
name: Python package
"on":
  pull_request:
    branches: ["master"]
  push:
    branches: ["master"] # cache from master shared with child branches

jobs:
  build:
    runs-on: ${{ vars.RUNNER_NAME }}
    container:
      image: registry.pyn.ru/python3.12-node22-bookworm-building:2025.01.11
      credentials:
        username: ${{ secrets.REGISTRY_USER }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    steps:
      - name: Checkout
        uses: https://src.pyn.ru/actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Install poetry
        run: |
          python -m pip install poetry

      - name: Install package
        run: |
          poetry install

      - name: Test with pytest
        run: |
          python -m poetry run pytest

      # true if cache-hit occured on the primary key
      - run: echo '${{ steps.pinstall.outputs.cache-hit }}'
#      - name: Lint with flake8
#        run: |
#          # stop the build if there are Python syntax errors or undefined names
#          # flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
#          # exit-zero treats all errors as warnings
#          flake8 . --count --exit-zero --max-complexity=10 --statistics
